export const WEAPONS = {
  ROCK: "rock",
  PAPER: "paper",
  SCISSORS: "scissors",
};

export const ACTIONS = {
  DRAW: "DRAW",
  PLAYERNAME: "PLAYERNAME",
  PLAYERWIN: "PLAYERWIN",
  COMPUTERWIN: "COMPUTERWIN",
  RESET: "RESET",
  CHANGE_USER: "CHANGE_USER",
  SET_SERIES: "SET_SERIES",
};
